spring:
  application:
    name: content-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql1234
    url: jdbc:mysql://localhost:3306/xc_content?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf8

#日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml